name: cipeats
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0

  flutter_riverpod: ^2.4.0
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^0.3.0
  mockito: ^5.4.4
  build_runner: ^2.4.0
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/Ayam_Geprek.png
    - assets/images/Bakara_Goreng.png
    - assets/images/ChickonCup.png
    - assets/images/Kentang_Goreng.png
    - assets/images/Mie_Kanton.png
    - assets/images/Nasi_Gila.png
    - assets/images/Nasi_Goreng.png
    - assets/images/Pisang_Goreng.png
    - assets/images/Prasmanan.png
    - assets/images/WarungAw.png
    - assets/images/logo.png
